name: Selenium CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "*/2 * * * *"       # Run every 2 minutes
  workflow_dispatch:             # Manual trigger

# Prevent overlapping runs
concurrency:
  group: selenium-tests
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Full Maven isolation: NO reuse of old ~/.m2 (prevents Lombok issues)
    - name: Prepare clean Maven repository
      run: |
        echo "Using isolated Maven repo"
        export MAVEN_OPTS="--add-opens jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED"

    - name: Run Dependency Tree (debugging)
      run: mvn -B -DoutputFile=dependency-tree.txt dependency:tree

    # Run tests using a CLEAN Maven repository (no cache)
    - name: Run Selenium Tests
      env:
        MAVEN_OPTS: "--add-opens jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED"
      run: mvn -B clean test -Dmaven.repo.local=.m2_repo -DbrowserMode=headless

    # Upload reports
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: Selenium-Reports
        path: |
          reports/**
          target/surefire-reports/**
        if-no-files-found: warn
